### ISSUE TITLE
Host / Location

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webvr-content-workshop#1]
Primary interest is to organize this in Europe to reach out to the European community

We have a tentative offer from BBC in London

**Comment by dontcallmedom** [comment]
the hosting will also have an impact on the dates (#2) and the number of participants we can welcome

**Comment by diekus-zz** [comment]
Options for venues in Lille, Brussels, Paris or London. Looking for venues that can host around 120 people for 3 days.
