### ISSUE TITLE
Optimizing delivery of 360° videos to VR headsets on the Web 

### ISSUE THREAD

**Issue by delapuente** [w3c/webvr-content-workshop#23]
Know the state of the art in 360 video formats. Identify the acceptable trade-offs of each alternative. Identify interaction opportunities and foresee the natural evolution of 360 content. 

* Limits of high-resolution omnidirectional video for the web (Rick Hindriks, @SwiftPengu)

**Comment by SwiftPengu** [comment]
There is also a discrepancy between the maximum supported texture size (I managed to use up to textures with a resolution of 16K, and decodeable video size (4K), also this is different based on the user device.
Therefore, I would like to talk about using high-resolution videos in WebVR.

**Comment by delapuente** [comment]
Sure thing @SwiftPengu , can you gave us a one-sentence description for the lightning talk?

**Comment by SwiftPengu** [comment]
I'd suggest "Limits of high-resolution omnidirectional video for the web".

**Comment by delapuente** [comment]
I just opened a resources issue on GitHub for 360º content #30. Does anyone want to bring the topic of subtitles to the table?

**Comment by delapuente** [comment]
Merged with #18
