### ISSUE TITLE
 Mapping the impact of ongoing evolutions of the Web Platform (Web Assembly, WebGPU, streams) on WebVR authoring 

### ISSUE THREAD

**Issue by delapuente** [w3c/webvr-content-workshop#24]
Know the key Web technologies improving performance across the Web Platform. Anticipate the impact of these actors on WebVR experiences. Identify lack of initiatives and the areas of development not covered. 

* Usage of WebRTC in combining communication with WebVR. Technologies for efficiently processing realtime media (video, pointclouds, lightfields...),

**Comment by SwiftPengu** [comment]
Usage of WebRTC in combining communication with WebVR. Technologies for efficiently processing realtime media (video, pointclouds, lightfields...),

**Comment by delapuente** [comment]
Merged with #31
