### ISSUE TITLE
UI/UX in WebVR

### ISSUE THREAD

**Issue by delapuente** [w3c/webvr-content-workshop#26]
Share good and bad practices regarding interaction patterns; discuss ways of displaying traditional 2D content on the web.

* A whirlwind tour of the most frequent UX cliffs in VR development and how to avoid them (Martin Splitt @AVGP)

**Comment by AVGP** [comment]
I have something to say about this one as I've seen some... things...with customers and I've committed sins myself.

**Comment by delapuente** [comment]
Sure, @AVGP this is an identified topic. So it was not among the expression of interest in the survey but a lot of you referred to it in other answers. So, please, leave a one-sentence description for a lightning talk. If it is finally not accepted as a plenary session, we will move it to a follow-up session.

**Comment by AVGP** [comment]
Alright, here goes nothing:

> A whirlwind tour of the most frequent UX cliffs in VR development and how to avoid them

**Comment by SwiftPengu** [comment]
Would be interesting if we could talk about the use of controllers (e.g. pointing / grabbing / etc...) as well.

**Comment by AVGP** [comment]
Yup, input and controllers are part of this IMHO.

Also locomotion, UIs etc.

**Comment by delapuente** [comment]
Actually, I'm thinking of merging it with #22 or #19

**Comment by AVGP** [comment]
I could see merging #22, #19 feels like a vast and quite different (yet
related) topic. I wouldn't merge with #19 IMHO

**Comment by delapuente** [comment]
Merged with #22
